### ISSUE TITLE
Assign a shortcut to a script

### ISSUE THREAD

**Issue by pjhfggij** [architecture-building-systems/revitpythonshell#154]
**Is your feature request related to a problem? Please describe.**
I'm trying to invoke a script from a shortcut. Is it possible? Any ideas would be appreciated.

**Comment by thumDer** [comment]
I would use pyRevit for this.

**Comment by pjhfggij** [comment]
[lol](https://github.com/eirannejad/pyRevit/issues/2113#issuecomment-1962941342)
I just switched to C# - somehow it was simpler than using python

**Comment by thumDer** [comment]
that comment was valid in that context. in Revit you can only assign key shortcuts to commands that have a button on the ribbon. if you need a button you need pyrevit OR a complete addin you just did, but that is still much more effort than creating a pyrevit extension with a pushbutton bundle.

**Comment by pjhfggij** [comment]
have you seen how python is integrated in rhino? you can simply call you script with a command, it could be a file anywhere or even a named pipe if you feel creative. None of these two python projects come close to that level of simplicity that will draw users away faster than them realizing all the other parts of Revit API that will break in the future releases.

**Comment by thumDer** [comment]
You are comparing apples to oranges. Rhino's python integration is developed by McNeel by developers who are getting money for their work, so it has the support of the company behind it. pyRevit and RPS is developed by volunteers who want to help fellow engineers to use the Revit API without extensive .NET & C# knowledge. Autodesk doesn't really give a shit about it, they consider their job is done by providing the API. You target your rambling against the wrong people. You should go to the Revit API or Ideas or whatever forum where you can blow off steam instead of being so unjust and ungrateful.

**Comment by pjhfggij** [comment]
"engineers" and "without extensive .NET & C# knowledge" don't belong in a single sentence.
