### ISSUE TITLE
Hitting autocomplete after method calls crashes revit

### ISSUE THREAD

**Issue by gtalarico** [architecture-building-systems/revitpythonshell#39]
example:
element.get_BoundingBox().  ...
As soon as you hit _dot_ revit crashes....

Consistently reproduced on 2015 + 2016

**Comment by daren-thomas** [comment]
I have just tried this with the Revit 2017 version... instead of crashing
Revit, I get an error dialog:

[image: Inline image 1]

This was for a wall object (`<Autodesk.Revit.DB.Wall object at
0x000000000000002C [Autodesk.Revit.DB.Wall]>`). So, I think this is better.
Maybe we can backport this to the 2015 and 2016 versions?

If you do `bb = element.get_BoundingBox()` you might see another problem:

>>> element
﻿<Autodesk.Revit.DB.Wall object at 0x000000000000002C
 [Autodesk.Revit.DB.Wall]>
>>> bb = element.get_BoundingBox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_BoundingBox() takes exactly 1 argument (0 given)
>>>

Maybe that is why autocomplete crashes? I will probably have to look into
this, but I am also dreading it: The PythonConsole code is really hairy...

Thank you for reporting this! I have added it to my task list :)

**Comment by PMoureu** [comment]
with the release 2016.04.29 : crashes  (because  get_BoundingBox() needs the view argument)
with the release 2016.05.21 : catches error

maybe users still download April release from the README file ?

**Comment by gtalarico** [comment]
I definitely downloaded the installer from the readme @PMoreu! 
That would explain. I will to download the latest from the binary install from the source folder

**Comment by gtalarico** [comment]
Ps: I'm running it on revit 2015.
Looks like 04.29 is the latest...

**Comment by PMoureu** [comment]
@gtalarico, check this one :
https://github.com/architecture-building-systems/revitpythonshell/releases/download/2015.05.21/2015.05.21_Setup_RevitPythonShell_2015.exe

**Comment by PMoureu** [comment]
Hi @gtalarico, ten years later sorry....
I've tried to backport some changes to improve RPS on revit 2015, works fine for me.

If you still need it, you can try to replace the DLL from this output  : 
https://github.com/PMoureu/revitpythonshell/tree/master/DLL/2015

I need some advices to generate clean installers, next step...

**Comment by daren-thomas** [comment]
@PMoureu how can i help you generate clean installers? What is currently missing?

**Comment by PMoureu** [comment]
Hi Daren, thanks for the backing
Mostly, i'm lacking time to get into innosetup, and packaging stuff...
i managed to build the project because your config is ready-to-use by version, 
but i'm confused about selecting the right files for each release, with the different outputs, bin, obj...

Don't waste your time, i need to study this first

**Comment by daren-thomas** [comment]
OK. When you have questions, just ask!
